# Generated by Django 2.0 on 2018-02-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAAContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('phone', models.CharField(max_length=250, verbose_name='Phone')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
        ),
    ]
