# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosaic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('story', models.TextField(blank=True)),
                ('iaa_id', models.CharField(max_length=50)),
                ('iaa_permission_code', models.CharField(max_length=50)),
                ('place_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('period', models.CharField(max_length=50)),
                ('displayed_at', models.CharField(blank=True, max_length=200)),
                ('matriel', models.CharField(max_length=50)),
                ('dimen_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimen_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimen_area', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comments', models.TextField(blank=True)),
                ('bibliography', models.TextField(blank=True)),
                ('publications', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MosaicPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_priority', models.IntegerField(default=100)),
                ('picture', models.ImageField(upload_to=main.models.mosaic_dir)),
                ('negative_id', models.CharField(max_length=50)),
                ('photographer_name', models.CharField(max_length=100)),
                ('taken_at', models.CharField(blank=True, max_length=100)),
                ('picture_type', models.CharField(max_length=50)),
                ('taken_date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('mosaic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mosaic')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='mosaic',
            name='tags',
            field=models.ManyToManyField(to='main.Tags'),
        ),
    ]
