# Generated by Django 2.0 on 2017-12-25 10:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MosaicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('misp_rashut', models.CharField(max_length=200, verbose_name='Rashut number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('length', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Length')),
                ('width', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Width')),
                ('area', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Area')),
                ('rishayon', models.CharField(max_length=50, verbose_name='Rishayon')),
                ('materials', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('stone', 'Stone'), ('glass', 'Glass')], max_length=50, verbose_name='Material'), blank=True, size=None)),
                ('year', models.CharField(blank=True, max_length=200, verbose_name='Year')),
                ('displayed_at', models.CharField(blank=True, max_length=200, verbose_name='Displayed at')),
                ('bibliography', models.TextField(blank=True, verbose_name='Bibliography')),
            ],
        ),
        migrations.CreateModel(
            name='MosaicPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Cover image')),
                ('order_priority', models.IntegerField(default=100, verbose_name='Order priority')),
                ('picture', models.ImageField(upload_to=main.models.mosaic_dir, verbose_name='Picture')),
                ('negative_id', models.CharField(max_length=50, verbose_name='Negative ID')),
                ('photographer_name', models.CharField(blank=True, max_length=200, verbose_name='Photographer name')),
                ('taken_at', models.CharField(blank=True, max_length=200, verbose_name='Taken at')),
                ('picture_type', models.CharField(blank=True, choices=[('excavation', 'Excavation'), ('post_excavation', 'Post Excavation'), ('preservation', 'Preservation')], max_length=50, verbose_name='Picture type')),
                ('taken_date', models.DateField(blank=True, null=True, verbose_name='Taken date')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('mosaic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='main.MosaicItem', verbose_name='Mosaic')),
            ],
        ),
        migrations.CreateModel(
            name='MosaicSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('site_id', models.CharField(max_length=200, verbose_name='Site ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin')),
                ('story', models.TextField(blank=True, verbose_name='Story')),
                ('period', models.CharField(blank=True, choices=[('byzantine', 'Byzantine')], max_length=50, verbose_name='Period')),
                ('video_id', models.CharField(blank=True, max_length=50, verbose_name='Youtube video ID')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_he', models.CharField(max_length=100)),
                ('tag_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mosaicitem',
            name='mosaic_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.MosaicSite', verbose_name='Mosaic site'),
        ),
        migrations.AddField(
            model_name='mosaicitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mosaic_items', to='main.Tag', verbose_name='Tags'),
        ),
    ]
