# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mosaic',
            old_name='matriel',
            new_name='material',
        ),
    ]
