# Generated by Django 2.0 on 2017-12-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171225_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosaicitem',
            name='bibliography',
        ),
        migrations.RemoveField(
            model_name='mosaicitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mosaicpicture',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='mosaicpicture',
            name='photographer_name',
        ),
        migrations.RemoveField(
            model_name='mosaicsite',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='mosaicsite',
            name='story',
        ),
        migrations.RemoveField(
            model_name='mosaicsite',
            name='title',
        ),
        migrations.AddField(
            model_name='mosaicitem',
            name='bibliography_en',
            field=models.TextField(blank=True, verbose_name='Bibliography english'),
        ),
        migrations.AddField(
            model_name='mosaicitem',
            name='bibliography_he',
            field=models.TextField(blank=True, verbose_name='Bibliography hebrew'),
        ),
        migrations.AddField(
            model_name='mosaicitem',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description english'),
        ),
        migrations.AddField(
            model_name='mosaicitem',
            name='description_he',
            field=models.TextField(blank=True, verbose_name='Description hebrew'),
        ),
        migrations.AddField(
            model_name='mosaicpicture',
            name='comments_en',
            field=models.TextField(blank=True, verbose_name='Comments english'),
        ),
        migrations.AddField(
            model_name='mosaicpicture',
            name='comments_he',
            field=models.TextField(blank=True, verbose_name='Comments hebrew'),
        ),
        migrations.AddField(
            model_name='mosaicpicture',
            name='photographer_name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Photographer name english'),
        ),
        migrations.AddField(
            model_name='mosaicpicture',
            name='photographer_name_he',
            field=models.CharField(blank=True, max_length=200, verbose_name='Photographer name hebrew'),
        ),
        migrations.AddField(
            model_name='mosaicsite',
            name='origin_en',
            field=models.CharField(default='', max_length=100, verbose_name='Origin english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosaicsite',
            name='origin_he',
            field=models.CharField(default='', max_length=100, verbose_name='Origin hebrew'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosaicsite',
            name='story_en',
            field=models.TextField(blank=True, verbose_name='Story english'),
        ),
        migrations.AddField(
            model_name='mosaicsite',
            name='story_he',
            field=models.TextField(blank=True, verbose_name='Story hebrew'),
        ),
        migrations.AddField(
            model_name='mosaicsite',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Title english'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosaicsite',
            name='title_he',
            field=models.CharField(default='', max_length=200, verbose_name='Title hebrew'),
            preserve_default=False,
        ),
    ]
