# Generated by Django 2.0 on 2017-12-17 20:22

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171210_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='bibliography',
            field=models.TextField(blank=True, null=True, verbose_name='Bibliography'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='dimen_length',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='dimen_width',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='displayed_at',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Displayed at'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='iaa_id',
            field=models.CharField(max_length=50, verbose_name='IAA ID'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='iaa_permission_code',
            field=models.CharField(max_length=50, verbose_name='IAA permission code'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='material',
            field=models.CharField(max_length=50, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='origin',
            field=models.CharField(max_length=100, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='period',
            field=models.CharField(max_length=50, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='place_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place name'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='publications',
            field=models.TextField(blank=True, null=True, verbose_name='Publications'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mosaics', to='main.Tags', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='mosaicpicture',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='mosaicpicture',
            name='mosaic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='main.Mosaic', verbose_name='Mosaic'),
        ),
        migrations.AlterField(
            model_name='mosaicpicture',
            name='negative_id',
            field=models.CharField(max_length=50, verbose_name='Negative ID'),
        ),
        migrations.AlterField(
            model_name='mosaicpicture',
            name='photographer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Photographer name'),
        ),
        migrations.AlterField(
            model_name='mosaicpicture',
            name='picture',
            field=models.ImageField(upload_to=main.models.mosaic_dir, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='mosaicpicture',
            name='picture_type',
            field=models.CharField(max_length=50, verbose_name='Picture type'),
        ),
        migrations.AlterField(
            model_name='mosaicpicture',
            name='taken_at',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Taken at'),
        ),
        migrations.AlterField(
            model_name='mosaicpicture',
            name='taken_date',
            field=models.DateField(verbose_name='Taken date'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
