# Generated by Django 2.0 on 2018-01-01 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171231_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaicitem',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='mosaicitem',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='mosaicitem',
            name='materials',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('stone', 'Stone'), ('glass', 'Glass')], max_length=50, verbose_name='Material'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='mosaicitem',
            name='rishayon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rishayon'),
        ),
        migrations.AlterField(
            model_name='mosaicitem',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='mosaicpicture',
            name='picture_type',
            field=models.CharField(blank=True, choices=[('excavation', 'Excavation'), ('conservation', 'Conservation'), ('current', 'Current')], max_length=50, verbose_name='Picture type'),
        ),
        migrations.AlterField(
            model_name='mosaicsite',
            name='archeological_context',
            field=models.CharField(blank=True, choices=[('church', 'Church'), ('synagogue', 'Synagogue'), ('public', 'Public building'), ('private', 'Private building')], max_length=50, verbose_name='Archeological context'),
        ),
    ]
