# Generated by Django 2.0 on 2018-01-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180101_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosaicsite',
            name='archeological_context',
        ),
        migrations.AddField(
            model_name='mosaicsite',
            name='archaeological_context',
            field=models.CharField(blank=True, choices=[('church', 'Church'), ('synagogue', 'Synagogue'), ('public', 'Public building')], max_length=50, verbose_name='Archaeological context'),
        ),
        migrations.AlterField(
            model_name='mosaicitem',
            name='rishayon',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rishayon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosaicpicture',
            name='picture_type',
            field=models.CharField(blank=True, choices=[('excavation', 'Excavation'), ('post_excavation', 'Post Excavation'), ('preservation', 'Preservation')], max_length=50, verbose_name='Picture type'),
        ),
    ]
