# Generated by Django 2.0 on 2018-01-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180103_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaicsite',
            name='archaeological_context',
            field=models.CharField(blank=True, choices=[('church', 'Church'), ('synagogue', 'Synagogue'), ('public', 'Public building'), ('private', 'Private building')], max_length=50, verbose_name='Archaeological context'),
        ),
    ]
