# Generated by Django 2.0 on 2018-01-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180110_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='featured',
            field=models.BooleanField(default=True, verbose_name='Is featured?'),
        ),
    ]
