# Generated by Django 2.0 on 2018-01-15 19:58

from django.db import migrations

from main.get_data import add_info_to_pictures


def create_info(apps, schema_editor):
    add_info_to_pictures()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_tag_featured'),
    ]

    operations = [
        migrations.RunPython(create_info)
    ]
