# Generated by Django 2.0 on 2018-02-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180115_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('site_name_he', models.CharField(blank=True, max_length=255, verbose_name='Site name Hebrew')),
                ('site_name_en', models.CharField(blank=True, max_length=255, verbose_name='Site name English')),
                ('admin_email_from', models.CharField(blank=True, max_length=255, verbose_name='Admin email from')),
                ('admin_email_to', models.EmailField(blank=True, max_length=255, verbose_name='Admin email to')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
            ],
            options={
                'verbose_name': 'General settings',
            },
        ),
    ]
