# Generated by Django 2.0 on 2018-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_generalsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='about',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About English'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='about_he',
            field=models.TextField(blank=True, null=True, verbose_name='About Hebrew'),
        ),
    ]
