# Generated by Django 2.0.2 on 2018-03-02 09:06

from django.db import migrations


def split_sites(apps, schema_editor):
    MosaicSite = apps.get_model('main', 'MosaicSite')
    for site in MosaicSite.objects.all():
        site_id = site.site_id
        for i in range(1, 6):
            site.pk = None
            site.site_id = '{}-new{}'.format(site_id, i)
            site.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0010_auto_20180205_2033'),
    ]

    operations = [
        migrations.RunPython(split_sites),
    ]
