# Generated by Django 2.0 on 2018-04-16 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180305_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_category_he', models.CharField(max_length=100, verbose_name='Tag category hebrew')),
                ('tag_category_en', models.CharField(max_length=100, verbose_name='Tag category english')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_en',
            field=models.CharField(max_length=100, verbose_name='Tag english'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_he',
            field=models.CharField(max_length=100, verbose_name='Tag hebrew'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='main.TagCategory', verbose_name='Tag category'),
        ),
    ]
